networks:
  keycloak: { }

volumes:
  keycloak-pgsql: { }

services:
  keycloak-pgsql:
    container_name: keycloak-pgsql
    image: docker.io/bitnami/postgresql:15-debian-11
    volumes:
      - keycloak-pgsql:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: "keycloak"
      POSTGRESQL_USERNAME: "keycloak"
      POSTGRESQL_PASSWORD: "keycloak_pw"
    networks:
      - keycloak

  keycloak:
    container_name: keycloak
    image: ghcr.io/mangadex-pub/keycloak:1.2.0-kc21.1.1
    depends_on:
      - keycloak-pgsql
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev" ]
    command:
      - --db-url="jdbc:postgresql://keycloak-pgsql:5432/keycloak"
      - --db-username="keycloak"
      - --db-password="keycloak_pw"
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    links:
      - keycloak-pgsql
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/health/ready" ]
      interval: 5s
      timeout: 5s
    ports:
      - "8080:8080"
    volumes:
      - ./providers/theme/src/main/resources/theme/mangadex:/opt/keycloak/themes/mangadex:ro
    environment:
      JAVA_OPTS: "-XX:+UseShenandoahGC -Xms512m -Xmx512m"
      KC_DB: "postgres"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_FEATURES: "declarative-user-profile,update-email"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "password"
    networks:
      - keycloak
